globality-corp/nodule-graphql

package.json, src/middleware/jwt/__tests__/passBasicAuth.test.js, src/middleware/jwt/index.js, src/middleware/jwt/passBasicAuth.js, yarn.lock
Why? Some of our middlewares have basic auth built in, but our apps use jwt
auth. We can get arround this by adding a middleware to transform auth from the
basic auth format to the jwt format.
- Transform basic auth into bearer auth
- add test coverage
- pull realm from jwt config
=>  Add basic auth transformation.

src/routes/graphiql.js
Why?
The endpoint url config key is derived from environment config loader, which
turns `FOO_URL` into `fooUrl` and not `fooURL`, this PR fixes the key and sets a
better default
=> [FIX] fixing graphiql endpoint url

package-lock.json, package.json, src/middleware/jwt/__tests__/middleware.test.js, src/middleware/jwt/middleware.js, src/middleware/jwt/passBasicAuth.js, yarn.lock
- Add the `nodule-logging` dependency
- Use it from a middleware and validate that tests don't fail when a nodule is
not configured
Build will fail until: https://github.com/globality-corp/nodule-logging/pull/7
=> Add a sample logger usage in nodule-graphql.

package.json, src/clients/logging.js, src/clients/openapi.js, yarn.lock
We turn off logging for OpenAPI client requests during testing as it produces a lot of noise.
Set the logging properties using setDefaults('logging', <logging parameters>) on the given service.
=> Add logging to OpenAPI client requests

README.md, package.json, src/index.js, src/modules/concurrency.js, src/services/README.md, src/services/batching/__tests__/wrapper.test.js, src/services/batching/batchRequests.js, src/services/batching/wrapper.js, src/services/core/__tests__/keys.test.js, src/services/core/keys.js, src/services/core/named.js, src/services/dedup/__tests__/wrapper.test.js, src/services/dedup/wrapper.js, src/services/index.js, src/services/wrapper.js, yarn.lock
* Includes batching and dedup functionality
* Supports adding more wrappers
Why?
There is a need to wrap OpenAPIClient definitions to inject additional functionality around all endpoints.
=> Add services functionality to nodule-graphql

.bumpversion.cfg, package.json, src/services/index.js
Why?
services['foo.bar'] = baz creates { 'foo.bar': baz } instead of { 'foo': { 'bar': baz } } as desired. 
As a result we do not properly override the client definitions and the services revert to using the original client definitions.
=> Fix setting services

.bumpversion.cfg, package.json, src/services/batching/__tests__/wrapper.test.js, src/services/dedup/__tests__/wrapper.test.js, src/services/dedup/wrapper.js
Why?
To enable batching/deduplication
=> Fix binding to loaders

src/services/dedup/__tests__/wrapper.test.js, src/services/dedup/wrapper.js
Why?
Dedup and batch requests should only exist for the life time of the request
=> Fix data loader issue

src/index.js, src/services/index.js
Why?
when using the batched wrapper, we need to use the named function for building
the batching configuration
=> exposing the named function to imports

.bumpversion.cfg, package.json, src/__tests__/enums.test.js, src/enums/index.js, src/index.js, yarn.lock
Why:
We have many Enums on our gateways. We use the "enum" package for this purpose. But graphql has a different `GraphQLEnumType` that has a different structure, which leads to us redefining the enum as a `GraphQLEnumType`. This utility attempts to provide an easy way to convert an `Enum` to a `GraphQLEnumType`.
=> Create createGraphQLEnumType utility

.bumpversion.cfg, package.json
* bump logging version
* GLOB-28139 - allowing multiple requireArgs sets (#82)
Why?
Some service calls are called with different args in different context. This
change allows for multiple versions of the requireArgs parameter, without
breaking current usage of the API.
What I've done:
1. instead of using a single requireArgs list, we check against an array
of requiredArgs, and if one of the versions fits the passed arguments, we cache
2. added tests for multiple versions, while making sure current tests still pass
* bump to 0.28.0
=> Release/0.28.0 (#83)

.bumpversion.cfg, package.json, src/__tests__/routes.test.js, src/__tests__/services.js, src/routes/graphql.js, yarn.lock
Added a `formatError` for graphqlExpress
The format error function adds meaningful extensions to each error that are useful for clients to better diagnose and handle errors. Formatted error adhere to section 7.1.2 of the GraphQL specification https://graphql.github.io/graphql-spec/June2018/#sec-Errors
=> Add formatError function to graphqlExpress options

src/services/caching/__tests__/logging.test.js, src/services/caching/logging.js
Part of [GLOB-38213]
Logging for GW caches was broken because of the following line:
```javascript
import { calculateExecuteTime } from '@globality/nodule-express';
```
This function isn't exported from `nodule-express`, but usefully it's duplicated within this library. This commit switches the import location so logging can work correctly.
[GLOB-38213]: https://globality.atlassian.net/browse/GLOB-38213
=> GLOB-38213 fix broken caching logging

CHANGELOG.md, package.json, scripts/pack-dev.sh, src/__tests__/app.js, src/__tests__/enums.test.js, src/__tests__/routes.test.js, src/routes/graphiql.js, src/routes/graphql.js, yarn.lock
Ticket: https://globality.atlassian.net/browse/GLOB-38999
Updated this package to use `apollo-server` v2. This update does not break the API or semantics. Everything will continue to work as before. Only internal changes were done.
Main changes:
1. updated `routes.graphql` to use new `ApolloServer` class
2. updated `routes.graphiql` to use the new GraphQL playground app
For (1), some changes had to be made to accommodate how a `ApolloServer` instance is created. For (2), graphiql has been replaced with a newer GQL tool called GraphQL playground (https://github.com/prisma-labs/graphql-playground)
Changes to this package has been tested against the styx GW. Everything continues to work as expected.
=> GLOB-38999: Upgrade library to use apollo server v2

.bumpversion.cfg, CHANGELOG.md, package.json
Major revision from v0.32.0 to v1.0.0. Addresses v0.32.0's semantic breaking change (upgraded to graphql@14.x)
See commit https://github.com/globality-corp/nodule-graphql/pull/95
=> major version bump 1.0.0

.bumpversion.cfg, CHANGELOG.md, package.json, src/__tests__/routes.test.js, src/routes/__tests__/graphql.test.js, src/routes/graphql.js
Updated `routes.graphql` to accept an apollo engine config (`routes.graphql.apolloEngine`). Can use the config to enable the Apollo engine in addition to applying specific Apollo Engine options such as API key, schema tag and what GQL variables and HTTP headers are sent to Apollo Graph Manager when tracing.
Deprecated graphql route `tracing` and `cacheControl` config options.
=> Add GraphQL route Apollo engine config

src/__tests__/routes.hideErrors.test.js, src/__tests__/routes.test.js, src/routes/graphql.js
This adds the ability to prevent error messages from bubbling up to
clients, given that said messages may contain otherwise sensitive data.
It defaults to false to preserve current behavior; it will need to be
overridden to take effect.
=> Add config to hide errors in message responses

package.json, src/middleware/jwt/middleware.js, yarn.lock
**Why?**
This PR is a part of fixing `express-jwt` vulnerability.
**What?**
- updated `express-jwt` to the 6.0.0
- updated `nodule-express` to the latest version
- provided `algorithms` param to jwt validator
=> GLOB-46007: Fix express-jwt vulnerability

package.json, src/middleware/jwt/__tests__/index.test.js, src/middleware/jwt/__tests__/middleware.test.js, src/middleware/jwt/index.js, src/middleware/jwt/middleware.js, src/routes/graphql.js, yarn.lock
updated create JWT middleware to take JWT token from different sources: body, cookie and header.
`middleware.jwt` used default jwt source (header) to avoid breaking changes.
Related to https://globality.atlassian.net/browse/GLOB-45370
=> JWT middleware: update to handle different source

.bumpversion.cfg, package.json
Bump version for release.
Minor version because we've changed a lot of dependencies: this feels a bit too big for a patch.
=> Release 1.6.0

.bumpversion.cfg, CHANGELOG.md, package.json, src/routes/__tests__/graphql.test.js, src/routes/__tests__/graphqlApolloPlugins.test.js, src/routes/graphql.js
Add ability to set up apollo plugins
Fixes [GLOB-51227]
I need to enable apollo server to receive configuration for plugins, so that I can setup plugins on our gateways. A use case for this is setting sentry support (read https://blog.sentry.io/2020/07/22/handling-graphql-errors-using-sentry).
- Add ability for the apollo server to receive plugins configuration from downstream modules. This should be optional, so if not provided the value should behave properly as before.
```
yarn test src/routes/__tests__/graphqlApolloPlugins.test.js
```
or
```
yarn test
```
- https://www.apollographql.com/docs/apollo-server/monitoring/metrics/
- https://blog.sentry.io/2020/07/22/handling-graphql-errors-using-sentry
- https://www.apollographql.com/docs/apollo-server/integrations/plugins/
[GLOB-51227]: …
=> GLOB-51227: add ability to set up apollo plugins

.circleci/config.yml, package.json, yarn.lock
Update dependencies to resolve security issues in production code.
(Some remain in `jest` and its dependencies, but would require some refactoring of unit tests to remove behaviour no longer supported by Jest)
=> Glob 54555: Resolve security issues

package.json, src/services/core/named.js
Before:
```
Received: [{"extensions": {"code": "INTERNAL_SERVER_ERROR"}, "locations": [{"column": 19, "line": 10}], "message": "Class constructor InternalServerError cannot be invoked without 'new'", "path": ["workspace", "items", 0, "taskOrderTemplate", "file", "boxToken"]}]
```
After
```
Received: [{"extensions": {"code": "HTTP-500"}, "locations": [{"column": 19, "line": 10}], "message": "crespi.boxTokens.retrieveFor.platformCompany not implemented", "path": ["workspace", "items", 0, "taskOrderTemplate", "file", "boxToken"]}]
```
tested using Styx unit tests and locally linked package.
=> Fix bug in raising error

package.json, src/services/index.js
This PR updates the `cloneClients` function to support the `options` argument for each operation.
To allow consumers to pass the `options` argument containing properties such as `additionalHeaders` when making requests to services e.g. `sphinx.moderationEvents.create(req, args, options)`.
Currently, such options are ignored as they are not passed here.
=> GLOB-76146: Support passing the options argument to operation requests

.bumpversion.cfg, package.json, src/__tests__/resolvers.js, src/resolvers/types.js
**Why?**
Sometimes, we may like to do some preparations involving a network call, before a resolver's aggregate function is called.
**What?**
Added the `preAggregate` hook that uses the same arguments that the `aggregate` and can make network requests.
=> Added preAggregate

src/resolvers/__tests__/resolver.test.js, src/resolvers/types.js
Usually, to avoid N+1 problem, we use batching configurations. However, there are cases where number of items we fetch is too big even when batching is enabled.
See this example query:
```
query projects {
projects {
id
name
proposals {
id
versions {
id
}
}
}
}
```
In reality, we most likely don't need to fetch all proposal versions at the same time when we fetch projects and even with proper batching, we might be fetching thousands of proposal versions. Instead, we should  take advantage of app navigation and break this down into e.g.:
```
query projects {
projects {
id
name
}
}
```
```
query projectProposals($projectId: ID!) {
projects(projectId: $projectId) {
id
name
proposals {
id
}
}
}
```
```
query projectProposalVersions($projectId: ID!, $proposalID: ID!) {
projects(projectId: …
```
=> Added overfetching guard to resolver class

package.json, src/routes/graphql.js
this is a forward port of https://github.com/globality-corp/nodule-graphql/commit/5ef6ccb3b6a37a9be33e64bca91012a94f9e0cde since styx is using v2
disables introspection for production styx (flagged as a security risk)
=> GLOB-76267 - disable introspection for styx prod

package.json, yarn.lock
Closes https://globality.atlassian.net/browse/GLOB-78942
To address the security vulnerabilities reported by [Snyk](https://app.snyk.io/org/globality/projects?groupBy=targets&before&after&searchQuery=nodule-graphql).
Updated a number of dependencies that were highlighted as containing security vulnerabilities.
- axios
- semver
- xss
- jsonwebtoken
- express-jwt
=> GLOB-78939: Update dependencies to fix security vulnerabilities

src/resolvers/context.js, src/resolvers/index.js, src/resolvers/types.js
We should have the request context available in the resolvers without passing through the context in code
=> Add request context
